### PR TITLE
new images

### PR DESCRIPTION
**Pull request by illudedPerception**
rotated images with Mesa Plains image + transform data (used in the railroadmap.ts)

Pine valley
transform = 'matrix(-93.81,0,0,93.81,199953,-199953)';

Lake valley
transform = 'matrix(92.5,0,0,-92.5,-197454,197454)';

Aurora falls
transform = 'matrix(140.9,0,0,-140.9,-300899.5,300459.5)';

Mesa plains
transform = 'matrix(140.9,0,0,-140.9,-300899.5,300459.5)';

### CODE REVIEW

**Comment by embix** [comment]
While having the images in their natural orientation is nice, the transform matrices you provided aren't in sync with the patched rendering. iirc you could multiply the matrix with a rotation factor/matrix to get the rotated matrix.

Using `transform = 'matrix(-93.81,0,0,93.81,199953,-199953)';` it's clearly wrong. (slot4 is a savegame from 11/2021, the other map is quite recent)

rro_slot4_in_release_orientation
rro_slot4_in_legacy_orientation
rro_ava_map

I naiivly tried `transform = 'matrix(93.81,0,0,-93.81,-199953,199953)';` but that clearly does not work either.

@illudedPerception if you wanna try your luck (or actually know, how to do this) you can look at 33bc8c3f4941efaa743604d800cc2ac324298f64 (the [spike-merge-illu-pr1](https://github.com/embix/railroad.studio/tree/spike-merge-illu-pr1) branch)

EDIT/PS/Aside: I broke the rendering of the legacy rotation button somewhere along the commits. It should only be visible for legacy savegames anyways.

**Comment by illudedPerception** [comment]
also try this `transform = 'matrix(-93.81,0,0,93.81,-199953,199953)';` atm i cant test it until tomorrow when i figure out how to get ur code to work locally for me
i dont know what to say, the transforms have allways worked perfect until, now and they export with the image from QGIS (program used for irl maps) and i did generate a image with some cords flipped in a new project yesterday and its still gave me the same transformations if i exported the image out of the program (or few points here or there off), Ue cords system is allready different from other game they have the X and Y switched but on top of that the dev decided to start messing with the maps out of the blue i dont know why

**Comment by illudedPerception** [comment]
for pine valley    transform = 'matrix(93.81,0,0,93.81,-199953,-199953)'; prob the others need the same treatment just remove 
image

**Comment by illudedPerception** [comment]
also the river is hand painted in so its not as accurate as you think, same for any other water painted in BTW :D

**Comment by illudedPerception** [comment]
lake valley transform = 'matrix(92.5,0,0,92.5,-197454,-197454)'; works (prob seems all of them want this done). Transformation is off by ~0.9-1.3m what is very good for the CRS i used in QGIS (what states to have a accuracy of 2m)
image 
the luck on your side sheesh, i did paint some of the industries a few updates back took me a solid 6-8 hours to get one of the gold update industries painted cause the transform thing is bunch of math and im not good at math :D

**Comment by illudedPerception** [comment]
closed the pull request cause i rebased my branch

**Comment by embix** [comment]
> the transform thing is bunch of math

It really is, and I only have used it briefly more than a decade ago. I currently don't have the motivation to get into it.

> closed the pull request cause i rebased my branch

According to GitHub this PR ist still open. But I'm okay with closing. Once maps and the required transform matrices are ready you can open another PR, probably best in the [main repo](https://github.com/scottanderson/railroad.studio) then.

**Comment by illudedPerception** [comment]
all map images are ready to go and i need to test a few more matrixes but, this code needs to be re written to work with 4 maps i kinda managed to do it in half a day to make it work with 3 maps and then still neo fixed parts of it 

```
private renderBackground(): Element {
        let image;
        let transform;
        if (this.railroad.settings.gameLevelName === 'LakeValley') {
            image = 'LakeValleyTopo.png';
            transform = 'matrix(-93.16,0,0,-93.16,197453,197453)';
            // image = 'LakeValleyMap2.png';
            // transform = 'matrix(-200,0,0,-200,200000,200000)';
        } else if (this.railroad.settings.gameLevelName === 'AuroraFalls') {
            image = 'AuroraFallsTopo.png';
            transform = 'matrix(-139.13,0,0,-139.13,300900,300900)';
        } else {
            image = 'PineValleyTopo.png';
            // transform = 'matrix(-96.80,0,0,-96.80,199951,199951)'; // works for old map file

            // for renewed rotated map (is 180deg wrong tho)
            // transform = 'matrix(-93.81,0,0,93.81,199953,-199953)';

            // orientation somewhat matches, but position/scale or both are off
            transform = 'matrix(93.81,0,0,-93.81,-199953,199953)';
        }
        return this.layers.background
            .image(image)
            .attr('transform', transform);
    }

```

**Pull request closed without merging**
